version: '3'

services:
  xchain_utxo_tracker:
    build: .
    volumes:
      - xchain_utxo_tracker_data:/data/
    networks: 
      - network1
    ports:
      - "3000:3000"
      
networks:
  network1:
    name: xchain_network
    external: true
    
volumes:
  xchain_utxo_tracker_data: