/*********************************************************************
 *
 * Copyright © 2025–2026 Dankest, LLC
 * Based on XChain Platform by Dankest, LLC – https://dankest.llc
 *
 * SPDX-License-Identifier: AGPL-3.0-or-later
 *
 * This file is part of XChain Platform. Licensed under the GNU Affero
 * General Public License v3.0 or later; see LICENSE.md. A commercial
 * license (without AGPL source-disclosure terms) is available -
 * contact legal@dankest.llc.
 *
 **********************************************************************
 *
 * XChain Platform - Canonical Coin Definition - Dogecoin (DOGE)
 *
 * SINGLE SOURCE OF TRUTH for all Dogecoin-specific facts. See coins/BTC.js for
 * the schema rationale and how coins/index.js applies network selection +
 * regtest-only env overrides. Pure data: no getConfig() switch, no env reads.
 *
 * DOGE is a native-fee chain (fees paid in the native coin), has no segwit, and
 * carries a Dogeparty name-ownership genesis snapshot on mainnet. Regtest reuses
 * Bitcoin-testnet address prefixes because Dogecoin v1.14.x regtest does.
 *
 ********************************************************************/
module.exports = {

    // ── IDENTITY ────────────────────────────────────────────────────────────
    tick:        'DOGE',
    fullName:    'dogecoin',
    displayName: 'Dogecoin',
    site:        'https://dogecoin.com',
    decimals:    8,

    confirmations: 60, // default cross-chain attestation depth (hub DEFAULT_CONFIRMATIONS)

    // ── PER-NETWORK PARAMS ──────────────────────────────────────────────────
    networks: {

        mainnet: {
            net: {
                messagePrefix:        '\x19Dogecoin Signed Message:\n',
                bip32:                { public: 0x02facafd, private: 0x02fac398 },
                pubKeyHash:           0x1e,
                scriptHash:           0x16,
                wif:                  0x9e,
                dustThreshold:        100000,
                supportsSegwit:       false,
                singleOpReturnPolicy: true, // DOGE/LTC enforce one OP_RETURN per tx
            },
            firstBlock: 6240000,
            addresses: {
                BURN:            'DChainBurnAddressXXXXXXXXXXXawc9pt',
                GAS:             'DGasfpttCnTijuuoAdiJ9sXJjG7vQ5pMkW',
                DONATE1:         'DDonate1RBcwGnCRNnVtwuCmQyWW1Gn25f', // Protocol Development
                DONATE2:         'DDonate2o3Sg4phybp92oFpkmv8S9ZhGSV', // Community Development
                FEE_DESTINATION: 'DFeesjvoMoVqd9UDuwDSAxzHMF5xZFgeG9', // native-fee destination (env-overridable)
                REWARD:          'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', // structural only; COLLECT/XCHAIN are BTC-only
                EXPLORER:        'DDonate3FCoUgi1bxW5r9c2p75uKTLw9qE', // display-only donation
            },
            // Dogeparty name-ownership injected at the DOGE mainnet start block.
            // LEDGER_HASH = sha256 of the bundled CSV; DUMP_HASH = sha256 of the
            // uncompressed bundled state dump. Frozen at launch.
            genesis: {
                block:      6240000,
                ledgerHash: '87abac0b03cbd24694f7c5e666425bdae6f9a9c51b826826bd4848bd4ade991b',
                dumpHash:   '81d3d2cb4714bc40ec12c2d1c8573040858ddf66e4ba89a05d44d86d3bffa0f1',
            },
        },

        testnet: {
            net: {
                messagePrefix:        '\x19Dogecoin Signed Message:\n',
                bip32:                { public: 0x0432a9a8, private: 0x0432a243 },
                pubKeyHash:           0x71,
                scriptHash:           0xc4,
                wif:                  0xf1,
                dustThreshold:        100000,
                supportsSegwit:       false,
                singleOpReturnPolicy: true,
            },
            firstBlock: 64800000,
            addresses: {
                BURN:            'nchainburnaddressXXXXXXXXXXXYKgF7W',
                GAS:             'ngasn6zHFzJ72zpk3DBKmXhD2XtszujSDW',
                DONATE1:         'ndonate1dE87UXUFf4gjyhPg7hfQRJXVXr',
                DONATE2:         'ndonate2wev8vKDgvd1DHhtJtvkRbn2usJ',
                FEE_DESTINATION: 'nfeesoodkv5UTFXcDeKcUU95QHFiK2Ggo7',
                REWARD:          'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
                EXPLORER:        'ndonate3xHD56SnmmSxbjX7UMSPfN7XmVA',
            },
            // Testnet launches CLEAN (genesis disabled); namespace stays open.
            genesis: { block: 0, ledgerHash: null, dumpHash: null },
        },

        regtest: {
            // Dogecoin v1.14.x regtest reuses Bitcoin-testnet prefixes
            // (pubKeyHash 0x6f, WIF 0xef, bip32 0x043587cf/0x04358394). Addresses
            // generated by the running node won't decode under 0x71.
            net: {
                messagePrefix:        '\x19Dogecoin Signed Message:\n',
                bip32:                { public: 0x043587cf, private: 0x04358394 },
                pubKeyHash:           0x6f,
                scriptHash:           0xc4,
                wif:                  0xef,
                dustThreshold:        100000,
                supportsSegwit:       false,
                singleOpReturnPolicy: true,
            },
            firstBlock: 0,
            addresses: {
                BURN:            'mvs8WdppEhzQLxfcYwrr1eoKA2nUFi55ff',
                GAS:             'mgasDTdKu5DsbW97qSRnE8raAuYpKMfmhg',
                DONATE1:         'mzdg8wGxgP3Jk45FuZPspumCL3Ruup37ob',
                DONATE2:         'mmXU8RU7q3BUsyT66rtw1H6P7B2ZZd9c5Y',
                FEE_DESTINATION: 'mfees5pa2HwNBonk5vG23aDWkN9fuDJib4',
                REWARD:          'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
                EXPLORER:        'n1AvTJLLSA1NHamHd5KFj9mRn6BEcwnVbf',
            },
            genesis: {
                $envOverrides: {
                    block:      { env: 'XCHAIN_GENESIS_BLOCK',       type: 'int', default: 0 },
                    ledgerHash: { env: 'XCHAIN_GENESIS_LEDGER_HASH', type: 'str', default: null },
                    dumpHash:   { env: 'XCHAIN_GENESIS_DUMP_HASH',   type: 'str', default: null },
                },
            },
        },
    },

    // ── COIN-LEVEL CONSENSUS PARAMS (network-independent) ────────────────────
    legacyFees: {
        ISSUANCE_FEE_TOKEN:          '0.25000000',
        ISSUANCE_FEE_SUBTOKEN:       '0.10000000',
        EXPIRATION_FEE_DEFAULT_DAYS: 90,
        EXPIRATION_FEE_FREE_DAYS:    182,
        EXPIRATION_FEE_PER_DAY:      '0.00136986',
    },

    GAS_PRICE:                        '0.00001',
    UNIFIED_EXPIRATION_FEE_FREE_DAYS: 90,
    FEE_PAYMENT_MODE:                 'native', // DOGE: native-only; informational, not read at runtime
    FEE_TOLERANCE_MIN:                '0.95',
    FEE_TOLERANCE_MAX:                '1.10',
    ORACLE_MAX_PRICE_AGE_SECONDS:     1800,
    VALIDATOR_QUERY_LIMIT:            1000,

    GAS_SCHEDULE: {
        ISSUE:                 100000,
        ISSUE_SUBTOKEN:        50000,
        EXPIRATION_PER_DAY:    550,
        OWNERSHIP_ESCROW:      50000,
        AIRDROP_PER_RECIPIENT: 100,
        DIVIDEND_PER_RECIPIENT: 100,
        VM_EXECUTE_BASE:       1000,
        VM_DEPLOY_BASE:        100000,
        VM_DEPLOY_PER_BYTE:    10,
        VM_STATE_READ:         100,
        VM_STATE_WRITE:        200,
        VM_STATE_DELETE:       100,
        VM_ORACLE_READ:        100,
        VM_CROSSCHAIN_READ:    100,
        VM_ATTEST_REQUEST:     5000,
        VM_XCALL_REQUEST:      2000,
        VM_XCALL_CALLBACK:     20000,
        VM_EMISSION:           500,
        VM_COMPUTATION:        1,
        VM_GUARD_GAS_CEILING:  200000,
    },

    STAKING: {
        COOLDOWN_BLOCKS:         10080, // ~7 days at ~1 min/block
        ACTIVATION_DELAY_BLOCKS: 60,    // ~60 min reorg protection at ~1 min/block
        CAPABILITIES: {},               // capability staking is BTC-only at the protocol level
    },
};
